# FAGLL03-add-field
FAGLL03 add field

GENERATE FAGLPOSYEXT

se37 run ITEM_STRUC_EXTENSION FM
basic_strucname = FAGLPOSY
EXT_STRUCNAME = FAGLPOSYEXT
EXT_FIELDS_TABNAME = T012S
I_LSTCL = D
X_TRANSPORT = X

